### ISSUE TITLE
UCTE import fail because of conflicting IDs

### ISSUE THREAD

**Issue by murgeyseb** [itesla/ipst-entsoe#22]
## Issue description
While trying to import the attached UCTE formatted file, the import fails because of conflicting IDs on a substation and a voltage level.

[importIssue.zip](https://github.com/itesla/ipst-entsoe/files/1204233/importIssue.zip)

## Logs of the import process.

[main] TRACE eu.itesla_project.ucte.network.io.UcteReader - Reading comment block
[main] TRACE eu.itesla_project.ucte.network.io.UcteReader - Reading node block
[main] TRACE eu.itesla_project.ucte.network.io.UcteReader - Reading line block
[main] TRACE eu.itesla_project.ucte.network.io.UcteReader - Reading transformer block
[main] TRACE eu.itesla_project.ucte.network.io.UcteReader - Reading regulation block
[main] DEBUG eu.itesla_project.ucte.network.io.UcteReader - UCTE file read in 1 ms
[main] TRACE eu.itesla_project.ucte.network.ext.UcteNetworkExt - Update substations...
[main] TRACE eu.itesla_project.ucte.network.ext.UcteNetworkExt - Define substation ISSUE2
[main] TRACE eu.itesla_project.ucte.network.ext.UcteNetworkExt - Define voltage level ISSUE24 as a group of [ISSUE241] nodes
[main] TRACE eu.itesla_project.ucte.network.ext.UcteNetworkExt - Define substation ISSUE
[main] TRACE eu.itesla_project.ucte.network.ext.UcteNetworkExt - Define voltage level ISSUE2 as a group of [ISSUE 21, ISSUE 22] nodes
[main] TRACE eu.itesla_project.ucte.network.ext.UcteNetworkExt - Define voltage level ISSUE4 as a group of [ISSUE 42, ISSUE 41] nodes
[main] TRACE eu.itesla_project.ucte.converter.UcteImporter - Create substation 'ISSUE2'
[main] TRACE eu.itesla_project.ucte.converter.UcteImporter - Create voltage level 'ISSUE24'
[main] TRACE eu.itesla_project.ucte.converter.UcteImporter - Create bus 'ISSUE241'
[main] TRACE eu.itesla_project.ucte.converter.UcteImporter - Create load 'ISSUE241_load'
[main] TRACE eu.itesla_project.ucte.converter.UcteImporter - Create substation 'ISSUE'
[main] TRACE eu.itesla_project.ucte.converter.UcteImporter - Create voltage level 'ISSUE2'

eu.itesla_project.commons.ITeslaException: The network importIssue already contains an object 'SubstationImpl' with the id 'ISSUE2'

	at eu.itesla_project.iidm.network.impl.IdentifiableAdderImpl.checkAndGetUniqueId(IdentifiableAdderImpl.java:57)
	at eu.itesla_project.iidm.network.impl.VoltageLevelAdderImpl.add(VoltageLevelAdderImpl.java:75)
	at eu.itesla_project.ucte.converter.UcteImporter.createBuses(UcteImporter.java:100)
	at eu.itesla_project.ucte.converter.UcteImporter.import_(UcteImporter.java:701)

**Comment by murgeyseb** [comment]
Seams to be a trim issue on geographical spot in UCTE node reader.
[This patch](https://github.com/itesla/ipst-entsoe/files/1204324/local_patch.txt) seams to solve the issue (and passes the available unit tests).
